### ISSUE TITLE
Proplem with HSPI

### ISSUE THREAD

**Issue by bikebastler** [mcauser/MicroPython-ESP8266-DHT-Nokia-5110#1]
Try to rebuild this project but get stuck at the points when using the HSPI
for example
`from machine import Pin, HSPI`
`spi = HSPI(baudrate=80000000, polarity=0, phase=0)`

instead i have to use
`from machine import Pin, SPI`
`spi = SPI(1,baudrate=80000000, polarity=0, phase=0)`

was there an update on micropython or Im doing something wrong?

**Comment by mcauser** [comment]
There was an update in MicroPython.
The syntax you used above is correct.
Have fixed in ab51bdf421b5fdfe2be9929235b051956a193f12
